spring.datasource.url=jdbc:mysql://localhost:3306/db_cinema?createDatabaseIfNotExist=true&serverTimezone=UTC&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=Lettera22!

# Hibernate crea le tabelle
spring.jpa.hibernate.ddl-auto=update

# Forza l'inizializzazione SQL solo DOPO che Hibernate ha creato le tabelle
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# --- AGGIUNGI SOLO QUESTO IN FONDO AL TUO FILE ---
jwt.secret=9a7b8c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b
jwt.expiration=3600000

